let englishToChinese: [Character:Character] = [
    "0":"零",
    "1":"壹",
    "2":"貳",
    "3":"叁",
    "4":"肆",
    "5":"伍",
    "6":"陸",
    "7":"柒",
    "8":"捌",
    "9":"玖",
    "a":"锕",
    "b":"币",
    "c":"车",
    "d":"吨",
    "e":"噁",
    "f":"阀",
    "g":"膏",
    "h":"化",
    "i":"爱",
    "j":"就",
    "k":"可",
    "l":"咯",
    "m":"姆",
    "n":"乸",
    "o":"毮",
    "p":"瞥",
    "q":"雀",
    "r":"绒",
    "s":"色",
    "t":"天",
    "u":"鱼",
    "v":"吁",
    "w":"我",
    "x":"鑫",
    "y":"潆",
    "z":"盏",
    "A":"阿",
    "B":"滗",
    "C":"楚",
    "D":"大",
    "E":"钶",
    "F":"否",
    "G":"根",
    "H":"铧",
    "I":"霭",
    "J":"精",
    "K":"钶",
    "L":"囖",
    "M":"么",
    "N":"年",
    "O":"哦",
    "P":"皮",
    "Q":"清",
    "R":"日",
    "S":"是",
    "T":"铜",
    "U":"雨",
    "V":"御",
    "W":"歪",
    "X":"星",
    "Y":"鸢",
    "Z":"拶",
]

let chineseToEnglish: [Character:Character] = [
    "零":"0",
    "壹":"1",
    "貳":"2",
    "叁":"3",
    "肆":"4",
    "伍":"5",
    "陸":"6",
    "柒":"7",
    "捌":"8",
    "玖":"9",
    "锕":"a",
    "币":"b",
    "车":"c",
    "吨":"d",
    "噁":"e",
    "阀":"f",
    "膏":"g",
    "化":"h",
    "爱":"i",
    "就":"j",
    "可":"k",
    "咯":"l",
    "姆":"m",
    "乸":"n",
    "毮":"o",
    "瞥":"p",
    "雀":"q",
    "绒":"r",
    "色":"s",
    "天":"t",
    "鱼":"u",
    "吁":"v",
    "我":"w",
    "鑫":"x",
    "潆":"y",
    "盏":"z",
    "阿":"A",
    "滗":"B",
    "楚":"C",
    "大":"D",
    "鹅":"E",
    "否":"F",
    "根":"G",
    "铧":"H",
    "霭":"I",
    "精":"J",
    "钶":"K",
    "囖":"L",
    "么":"M",
    "年":"N",
    "哦":"O",
    "皮":"P",
    "清":"Q",
    "日":"R",
    "是":"S",
    "铜":"T",
    "雨":"U",
    "御":"V",
    "歪":"W",
    "星":"X",
    "鸢":"Y",
    "拶":"Z",
]

public enum ConvertMode {
    case englishToChinese
    case chineseToEnglish
}

func alaphabetConvertor(_ char: Character, _ mode: ConvertMode) -> Character {
    if mode == .englishToChinese {
        if let c = englishToChinese[char] {
            return c
        } else {
            return char
        }
    } else {
        if let c = chineseToEnglish[char] {
            return c
        } else {
            return char
        }
    }
}
